# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='향수 코드 (A, B, C, D, E)')),
                ('tagtext', models.CharField(max_length=50, verbose_name='향수 설명 태그 텍스트')),
                ('imageurl_1_common', models.URLField(blank=True, max_length=500, null=True, verbose_name='Common일 경우 1번째 이미지 url')),
                ('imageurl_2_common', models.URLField(blank=True, max_length=500, null=True, verbose_name='Common일 경우 2번째 이미지 url')),
                ('imageurl_3_common', models.URLField(blank=True, max_length=500, null=True, verbose_name='Common일 경우 3번째 이미지 url')),
                ('imageurl_1_special', models.URLField(blank=True, max_length=500, null=True, verbose_name='Special일 경우 1번째 이미지 url')),
                ('imageurl_2_special', models.URLField(blank=True, max_length=500, null=True, verbose_name='Special일 경우 2번째 이미지 url')),
                ('imageurl_3_special', models.URLField(blank=True, max_length=500, null=True, verbose_name='Special일 경우 3번째 이미지 url')),
            ],
        ),
        migrations.CreateModel(
            name='PerfumeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_paragraph', models.TextField(verbose_name='향수 추천 문구')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.Perfume', verbose_name='추천 향수')),
            ],
        ),
        migrations.CreateModel(
            name='UserPerfume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend_type', models.IntegerField(blank=True, choices=[(1, 'COMMON'), (2, 'SPECIAL')], null=True, verbose_name='추천 타입(Special or Common)')),
                ('reason_text', models.TextField(verbose_name='추천 이유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 수정일')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.Perfume', verbose_name='추천 향수')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='유저')),
            ],
        ),
    ]
