# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name_as_id',
            field=models.CharField(default='', max_length=100, verbose_name='아이디로 사용하기 위한 이름'),
            preserve_default=False,
        ),
    ]
